"""delete position

Revision ID: 245989799911
Revises: f63535d3a7fc
Create Date: 2025-05-19 21:13:08.392736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '245989799911'
down_revision: Union[str, None] = 'f63535d3a7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_signs', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_signs', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
